export const data = [
    {
        id: 1,
        image: "hajj1.jpg",
        package : 'day17.JPG',
        name: "Hajj 17 Days",
        description: "A well-planned 17-day Hajj package with comprehensive services, including accommodation, meals, and ziarat.",
        rating: 5,
        reviews: 3,
        days: '17',
        maktab: 'B',
        airline: "In-Direct",
        sharing_price: '6370 USD',
        triple_bed_price: "6460 USD",
        double_bed_price: "6640 USD",
        payment_schedule: '100% payment advance at the time of booking ( Non refundable )',
        food_included: 'Madinah ( Half Board ), Azizia ( Breakfast, Lunch, Dinner), Mina (3 meals provided by Saudi company)',
        features: [
          "Meet & assist upon arrival at Jeddah Airport",
          "Complete accommodation at Madinah, Azizia as mentioned",
          "Airfare included in above package through any indirect airline",
          "Ziarat Makkah & Madinah",
          "Seat-by-seat transport (Luxury Air-conditioned Busses)",
          "Maktab services as per Saudi company",
        ],
        note: [
          "Expats in the USA, Canada, UK, Europe, etc. will have different prices based on their countries.",
          "Azizia rooms on a sharing basis",
          "Qurbani not included",
          "Stay in Azizia & Madinah can decrease or increase subject to availability.",
        ],
      },
    {
        id: 1,
        image: "hajj2.jpg",
        name: "Hajj 17 Days",
        package : 'day17.JPG',
        description: "A well-planned 17-day Hajj package with comprehensive services, including accommodation, meals, and ziarat.",
        days: '15',
        maktab: 'B',
        airline: "In-Direct",
        sharing_price: '6370 USD',
        triple_bed_price: "6460 USD",
        double_bed_price: "6640 USD",
        payment_schedule: '100% payment advance at the time of booking ( Non refundable )',
        food_included: 'Madinah ( Half Board ) , Azizia ( Breakfast , Lunch Dinner) , Mina 03 time meals provide by saudi company',
        features: [
            "Meet & assist upon arrival at Jeddah Airport",
            "Complete accommodation at Madinah & madinah & Azizia as mentioned",
            "Air fare included in above package through any indirect airline",
            "Ziarat Makkah & Madinah",
            "Seat ny seat transport ( Luxury AirCondition Busses )",
            "Maktab services as per saudi company",
        ],
        note: [
            "Expats in the USA, Canada , UK , Europe , Australia , Middle East , Far East , etc Will have different prices  based on their countries. If the ticket is purchased by yourself you can reduce USD 1100 from the above package cost ",
            "Azizia rooms on sharing basis",
            "Qurbani not included",
            "stay in Azizia & Madinah can be decrease of increase subject to available of seats",
        ],
    },
    {
        id: 2,
        image: "hajjpackage3.jpg",
        name: "Hajj 21 Days",
        package : 'day21.JPG',
        description: "A well-planned 21-day Hajj package with comprehensive services, including accommodation, meals, and ziarat.",
        days: '21',
        maktab: 'B',
        airline: "In-Direct",
        sharing_price: '6810 USD',
        triple_bed_price: "6900 USD",
        double_bed_price: "7250 USD",
        payment_schedule: '100% payment advance at the time of booking ( Non refundable )',
        food_included: 'Madinah ( Half Board ) , Azizia ( Breakfast , Lunch Dinner) , Mina 03 time meals provide by saudi company',
        features: [
            "Meet & assist upon arrival at Jeddah Airport",
            "Complete accommodation at Madinah & madinah & Azizia as mentioned",
            "Air fare included in above package through any indirect airline",
            "Ziarat Makkah & Madinah",
            "Seat ny seat transport ( Luxury AirCondition Busses )",
            "Maktab services as per saudi company",
        ],
        note: [
            "Expats in the USA, Canada , UK , Europe , Australia , Middle East , Far East , etc Will have different prices  based on their countries. If the ticket is purchased by yourself you can reduce USD 1100 from the above package cost ",
            "Azizia rooms on sharing basis",
            "Qurbani not included",
            "stay in Azizia & Madinah can be decrease of increase subject to available of seats",
        ],
    },
    {
        id: 3,
        image: "hajjpackage4.jpg",
        name: "Hajj 27 Days",
        package : 'day27.JPG',
        description: "A well-planned 27-day Hajj package with comprehensive services, including accommodation, meals, and ziarat.",
        days : '25',
        maktab : 'B',
        airline : "In-Direct",
        sharing_price : '7700 USD',
        triple_bed_price : "8050 USD",
        double_bed_price : "8760 USD",
        payment_schedule : '100% payment advance at the time of booking ( Non refundable )',
        food_included : 'Madinah ( Half Board ) , Azizia ( Breakfast , Lunch Dinner) , Mina 03 time meals provide by saudi company',
        features: [
          "Meet & assist upon arrival at Jeddah Airport",
          "Complete accommodation at Madinah & madinah & Azizia as mentioned",
          "Air fare included in above package through any indirect airline",
          "Ziarat Makkah & Madinah",
          "Seat ny seat transport ( Luxury AirCondition Busses )",
          "Maktab services as per saudi company",
        ],
        note: [
          "Expats in the USA, Canada , UK , Europe , Australia , Middle East , Far East , etc Will have different prices  based on their countries. If the ticket is purchased by yourself you can reduce USD 1100 from the above package cost ",
          "Azizia rooms on sharing basis",
          "Qurbani not included",
          "stay in Azizia & Madinah can be decrease of increase subject to available of seats",
        ],
      },
      {
        id: 1,
        image: "hajjpackage5.webp",
        name: "Hajj 17 Days",
        package : 'day172.JPG',
        description: "A well-planned 15-day Hajj package with comprehensive services, including accommodation, meals, and ziarat.",
        days : '15',
        maktab : 'B',
        airline : "In-Direct",
        sharing_price : '6280 USD',
        triple_bed_price : "6370 USD",
        double_bed_price : "6550 USD",
        payment_schedule : '100% payment advance at the time of booking ( Non refundable )',
        food_included : 'Madinah ( Half Board ) , Azizia ( Breakfast , Lunch Dinner) , Mina 03 time meals provide by saudi company',
        features: [
          "Meet & assist upon arrival at Jeddah Airport",
          "Complete accommodation at Madinah & madinah & Azizia as mentioned",
          "Air fare included in above package through any indirect airline",
          "Ziarat Makkah & Madinah",
          "Seat ny seat transport ( Luxury AirCondition Busses )",
          "Maktab services as per saudi company",
        ],
        note: [
          "Expats in the USA, Canada , UK , Europe , Australia , Middle East , Far East , etc Will have different prices  based on their countries. If the ticket is purchased by yourself you can reduce USD 1100 from the above package cost ",
          "Azizia rooms on sharing basis",
          "Qurbani not included",
          "stay in Azizia & Madinah can be decrease of increase subject to available of seats",
        ],
      },
];

