export const hajjData = [
  {
      id: 12,
      image: "hajj202528d.JPG",
      package : 'hajj202528d.JPG',
      name: "Hajj 28 Days",
      description: "A well-planned 28-day Hajj package with comprehensive services, including accommodation, meals, and ziarat.",
      rating: 5,
      reviews: 3,
      days: '28',
    },
  {
      id: 13,
      image: "hajj202515bd.JPG",
      name: "Hajj 15 Days",
      package : 'hajj202515bd.JPG',
      description: "A well-planned 15-day Hajj package with comprehensive services, including accommodation, meals, and ziarat.",
      days: '15',
  },
  {
      id: 14,
      image: "hajj202517d.JPG",
      name: "Hajj 28 Days",
      package : 'hajj202517d.JPG',
      description: "A well-planned 17-day Hajj package with comprehensive services, including accommodation, meals, and ziarat.",
      days: '21',
  },
  {
      id: 15,
      image: "hajj202528bd.JPG",
      name: "Hajj 28 Days",
      package : 'hajj202528bd.JPG',
      description: "A well-planned 28-day Hajj package with comprehensive services, including accommodation, meals, and ziarat.",
      days : '25',
    },
    {
      id: 16,
      image: "hajj202515d.JPG",
      name: "Hajj 15 Days",
      package : 'hajj202515d.JPG',
      description: "A well-planned 15-day Hajj package with comprehensive services, including accommodation, meals, and ziarat.",
      days : '15',
    },
];

